[programs.localnet]
sol_race_staking = "9zCDvzC5e3QStC6ijSivcNvngRA2huaZsgER9GfPdGdD"
staking_gov="DrkYUKUUrdgznKjh6mFmM8dyXaMuhRqgi2F9u9QGxzf5"

[programs.devnet]
sol_race_staking = "9zCDvzC5e3QStC6ijSivcNvngRA2huaZsgER9GfPdGdD"
staking_gov="DrkYUKUUrdgznKjh6mFmM8dyXaMuhRqgi2F9u9QGxzf5"

[programs.testnet]
sol_race_staking = "9zCDvzC5e3QStC6ijSivcNvngRA2huaZsgER9GfPdGdD"
staking_gov="DrkYUKUUrdgznKjh6mFmM8dyXaMuhRqgi2F9u9QGxzf5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/supasinliulaks/.config/solana/localnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy_idl = "rm -rf frontend/src/api/idl && mkdir -p frontend/src/api/idl && cp -r target/idl/ frontend/src/api/idl"