[programs.localnet]
sol_race_staking = "FkqkswBdMknF3NFxjBFTyVXuCRqBxQMoyLizhPfYebYX"
verify_nft="DxAKuEXYPyTJDoN1qMtLEf8Gf9R2cs3z4aH9MJijsp77"
candy_machine = "72jjPUnGRbx1uSQr9z7RVdUsAaDXgQrPz8Ji8wq5MH4x"
candy_core = "EZfQMJmBpjDxVYj8x9MK4tQ1rtnJrudsxYahqQVkS2QQ"

[programs.devnet]
sol_race_staking = "FkqkswBdMknF3NFxjBFTyVXuCRqBxQMoyLizhPfYebYX"
candy_machine = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
verify_nft="DxAKuEXYPyTJDoN1qMtLEf8Gf9R2cs3z4aH9MJijsp77"
candy_core = "EZfQMJmBpjDxVYj8x9MK4tQ1rtnJrudsxYahqQVkS2QQ"

[programs.testnet]
sol_race_staking = "FkqkswBdMknF3NFxjBFTyVXuCRqBxQMoyLizhPfYebYX"
candy_machine = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
verify_nft="DxAKuEXYPyTJDoN1qMtLEf8Gf9R2cs3z4aH9MJijsp77"
candy_core = "EZfQMJmBpjDxVYj8x9MK4tQ1rtnJrudsxYahqQVkS2QQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/Users/supasinliulaks/.config/solana/testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy_idl = "rm -rf frontend/src/api/idl && mkdir -p frontend/src/api/idl && cp -r target/idl/ frontend/src/api/idl"