[programs.localnet]
sol_race_core = "J15WvsBaKL81rDA5kdjEpmdUGC7Y7dR9iMUbwevDkbdq"


[programs.devnet]
sol_race_core = "J15WvsBaKL81rDA5kdjEpmdUGC7Y7dR9iMUbwevDkbdq"


[programs.testnet]
sol_race_core = "J15WvsBaKL81rDA5kdjEpmdUGC7Y7dR9iMUbwevDkbdq"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/supasinliulaks/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy_idl = "rm -rf frontend/src/api/idl && mkdir -p frontend/src/api/idl && cp -r target/idl/ frontend/src/api/idl"
copy_types_frontend = "rm -rf frontend/src/api/solana/types && mkdir -p frontend/src/api/solana/types && cp -r target/types/ frontend/src/api/solana/types"
copy_types_backend = "rm -rf backend//src/idl && mkdir -p backend/src/idl && cp -r target/types/ backend/src/idl/"
copy_types_cli = "rm -rf scripts/cli/src/types && mkdir -p scripts/cli/src/types && cp -r target/types/ scripts/cli/src/types"