version: '3.1'

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'solana_hack_nft_dev'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: